const state={products:[],orders:[],categories:[],videos:[],accounts:[],logs:[],settings:null,stripe:null,currentUser:null,google:null};const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((c||0)/100);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
async function api(url,options={}){const r=await fetch(url,{...options,headers:{...(options.body instanceof Blob?{}:{'Content-Type':'application/json'}),...options.headers}});const d=await r.json().catch(()=>({}));if(r.status===401){showLogin();throw new Error('Please sign in again.')}if(!r.ok)throw new Error(d.error||'Request failed');return d}
function showLogin(){ $('#loginView').hidden=false;$('#appView').hidden=true;scrollTo(0,0) }function showApp(){ $('#loginView').hidden=true;$('#appView').hidden=false;$$('[data-developer-only]').forEach(el=>el.hidden=state.currentUser?.role!=='developer');scrollTo(0,0) }
function setView(name){if(name==='developer'&&state.currentUser?.role!=='developer')return;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#viewTitle').textContent={dashboard:'Overview',products:'Products',orders:'Orders',videos:'Video Projects',settings:'Settings',developer:'Developer'}[name];if(name==='developer')loadDeveloper()}
function render(){
  $('#statSales').textContent=money(state.orders.filter(o=>o.payment_status==='paid').reduce((s,o)=>s+o.amount_total,0));$('#statOrders').textContent=state.orders.filter(o=>o.payment_status==='paid').length;$('#statProducts').textContent=state.products.filter(p=>p.active).length;$('#statShipping').textContent=state.orders.filter(o=>o.payment_status==='paid'&&!['shipped','delivered','cancelled'].includes(o.fulfillment_status)).length;
  const orderRow=o=>`<tr><td><b>${new Date(o.created_at).toLocaleDateString()}</b><br><small>${o.id.slice(0,8)}</small></td><td>${esc(o.customer_name||'—')}<br><small>${esc(o.customer_email||'')}</small></td><td>${o.items.map(i=>`${i.quantity}× ${esc(i.product_name)}${i.variant?` (${esc(i.variant)})`:''}`).join('<br>')}</td><td>${money(o.amount_total)}</td><td><span class="badge ${esc(o.payment_status)}">${esc(o.payment_status)}</span></td><td><span class="badge ${esc(o.fulfillment_status)}">${esc(o.fulfillment_status)}</span></td><td><button class="mini-button" data-order="${o.id}">Manage</button></td></tr>`;
  $('#orderRows').innerHTML=state.orders.length?state.orders.map(orderRow).join(''):'<tr><td colspan="7">No orders yet.</td></tr>';$('#recentOrders').innerHTML=state.orders.length?state.orders.slice(0,5).map(o=>`<tr><td>${o.id.slice(0,8)}</td><td>${esc(o.customer_name||o.customer_email||'Pending')}</td><td>${money(o.amount_total)}</td><td><span class="badge ${esc(o.payment_status)}">${esc(o.payment_status)}</span></td><td><span class="badge ${esc(o.fulfillment_status)}">${esc(o.fulfillment_status)}</span></td></tr>`).join(''):'<tr><td colspan="5">No orders yet.</td></tr>';
  $('#productRows').innerHTML=state.products.length?state.products.map(p=>`<tr><td><div style="display:flex;gap:12px;align-items:center">${p.image_url?`<img class="thumb" src="${esc(p.image_url)}" alt="" loading="lazy" decoding="async">`:'<span class="thumb"></span>'}<div><b>${esc(p.name)}</b><br><small>${esc(p.category)}</small></div></div></td><td>${money(p.price_cents)}</td><td>${p.inventory}</td><td><span class="badge">${p.active?'Live':'Hidden'}</span></td><td><button class="mini-button" data-product="${p.id}">Edit</button></td></tr>`).join(''):'<tr><td colspan="5">Add the first product to open the shop.</td></tr>';
  const s=state.stripe||{};$('#stripeStatus').textContent=s.charges_enabled?'Ready for payments':s.connected?'Finish setup':'Not connected';$('#stripeStatus').classList.toggle('good',!!s.charges_enabled);$('#connectStripe').textContent=s.connected?'Continue Stripe setup':'Connect Stripe';
}
function renderCategories(){
  $('#categoryList').innerHTML=state.categories.length?state.categories.map(c=>`<span class="category-chip">${esc(c.name)}<button type="button" data-delete-category="${c.id}" aria-label="Delete ${esc(c.name)}">×</button></span>`).join(''):'<span class="error">Create a category before adding products.</span>';
  const select=$('#productForm').category,current=select.value;select.innerHTML=state.categories.map(c=>`<option value="${esc(c.name)}">${esc(c.name)}</option>`).join('');if(state.categories.some(c=>c.name===current))select.value=current;
  $('#newProduct').disabled=!state.categories.length;
}
const fileSize=n=>n?`${(Number(n)/1024/1024).toFixed(Number(n)>1024*1024*1024?1:0)} MB`:'—';
function renderVideos(){const dev=state.currentUser?.role==='developer';$('#videoRows').innerHTML=state.videos.length?state.videos.map(v=>`<tr><td><b>${esc(v.title)}</b><br><small>${esc(v.notes||'')}</small></td><td><span class="badge ${esc(v.status)}">${esc(v.status.replaceAll('_',' '))}</span></td><td>${v.original_file_id?`<a class="mini-button" href="/api/portal?action=video-download&id=${v.id}&kind=original">Download ${fileSize(v.original_size)}</a>`:'Waiting for upload'}</td><td>${v.final_file_id?`<a class="mini-button" href="/api/portal?action=video-download&id=${v.id}&kind=final">Download ${fileSize(v.final_size)}</a>`:dev?`<input id="final-${v.id}" type="file" accept="video/*,.mov,.mkv,.mxf" hidden><button class="mini-button" data-final="${v.id}">Upload final</button>`:'Not ready'}</td><td>${dev?`<select class="mini-button" data-video-status="${v.id}">${['uploaded','editing','review','complete'].map(s=>`<option ${s===v.status?'selected':''}>${s}</option>`).join('')}</select>`:''}</td></tr>`).join(''):'<tr><td colspan="5">No video projects yet.</td></tr>'}
function renderDeveloper(){const g=state.google||{};$('#googleCallback').textContent=g.callback_url||location.origin+'/api/google/callback';$('#driveStatus').textContent=g.connected?`Connected · ${g.email||'Google Drive'}`:g.configured?'Credentials saved — connect Drive':'Not configured';$('#driveStatus').classList.toggle('good',!!g.connected);$('#accountRows').innerHTML=state.accounts.map(a=>`<tr><td><b>${esc(a.username)}</b></td><td>${esc(a.role)}</td><td><span class="badge ${a.active?'paid':'pending'}">${a.active?'Active':'Disabled'}</span></td><td class="row-actions"><button class="mini-button" data-toggle-account="${a.id}" data-active="${a.active}">${a.active?'Disable':'Enable'}</button><button class="mini-button" data-delete-account="${a.id}">Delete</button></td></tr>`).join('');$('#logRows').innerHTML=state.logs.map(l=>`<tr><td>${new Date(l.created_at).toLocaleString()}</td><td>${esc(l.username||'System')}</td><td>${esc(l.action)}</td><td><small>${esc(JSON.stringify(l.details||{}))}</small></td></tr>`).join('')||'<tr><td colspan="4">No activity yet.</td></tr>'}
async function loadDeveloper(){if(state.currentUser?.role!=='developer')return;try{const[g,a,l]=await Promise.all([api('/api/portal?action=google-settings'),api('/api/portal?action=accounts'),api('/api/portal?action=logs')]);state.google=g;state.accounts=a.accounts;state.logs=l.logs;renderDeveloper()}catch(error){toast(error.message)}}
const DEMO_PRODUCTS=[{id:'11111111-1111-4111-8111-111111111111',name:'Point Study No. 01',description:'Original mixed-media basketball study.',price_cents:18000,image_url:'',category:'Original Art',variants:['Original'],inventory:1,active:true,featured:true},{id:'22222222-2222-4222-8222-222222222222',name:'Run the Floor Print',description:'Signed archival print.',price_cents:4500,image_url:'',category:'Prints',variants:['11 × 14','18 × 24'],inventory:24,active:true,featured:false},{id:'33333333-3333-4333-8333-333333333333',name:'Runnin’ Point Tee',description:'Heavyweight cotton tee.',price_cents:3800,image_url:'',category:'Merch',variants:['S','M','L','XL','2XL'],inventory:40,active:true,featured:false}];
async function load(){try{const [p,o,c,v,s,st]=await Promise.all([api('/api/products?admin=1'),api('/api/orders'),api('/api/portal?action=categories'),api('/api/portal?action=videos'),api('/api/settings'),api('/api/stripe/status').catch(()=>({connected:false}))]);state.products=p.products;state.orders=o.orders;state.categories=c.categories;state.videos=v.projects;state.settings=s.settings;state.stripe=st}catch{state.products=DEMO_PRODUCTS;state.orders=[];state.videos=[];state.categories=[{id:'demo-art',name:'Art'},{id:'demo-prints',name:'Prints'},{id:'demo-merch',name:'Merch'}];state.settings={store_name:"Runnin' Point Shop",store_description:'Preview collection — connect the database to save changes.',shipping_cents:0};state.stripe={connected:false};toast('Preview mode — database setup is still required')}const f=$('#settingsForm');f.store_name.value=state.settings.store_name;f.store_description.value=state.settings.store_description;f.shipping.value=(state.settings.shipping_cents/100).toFixed(2);renderCategories();renderVideos();render()}
function editProduct(product){const f=$('#productForm');f.reset();f.id.value=product?.id||'';f.name.value=product?.name||'';renderCategories();f.category.value=product?.category||state.categories[0]?.name||'';f.price.value=product?(product.price_cents/100).toFixed(2):'';f.inventory.value=product?.inventory??0;f.description.value=product?.description||'';f.variants.value=(product?.variants||[]).join(', ');f.image_url.value=product?.image_url||'';f.active.checked=product?.active??true;f.featured.checked=product?.featured??false;$('#editorTitle').textContent=product?'Edit product':'Add product';$('#deleteProduct').hidden=!product;$('#uploadPreview').innerHTML=product?.image_url?`<img src="${esc(product.image_url)}" alt="">`:'Choose an image below';$('#productEditor').hidden=false;$('#productEditor').scrollIntoView({behavior:'smooth'})}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;$('#loginError').hidden=true;try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:f.username.value,password:f.password.value})});state.currentUser=d.user;showApp();await load()}catch(error){$('#loginError').textContent=error.message;$('#loginError').hidden=false}};
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>setView(b.dataset.jump));$('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});showLogin()};$('#newProduct').onclick=()=>editProduct();$('#closeEditor').onclick=()=>$('#productEditor').hidden=true;
$('#imageFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('#uploadPreview').textContent='Uploading…';try{const d=await api('/api/upload',{method:'POST',headers:{'Content-Type':file.type},body:file});$('#productForm').image_url.value=d.url;$('#uploadPreview').innerHTML=`<img src="${esc(d.url)}" alt="">`}catch(error){$('#uploadPreview').textContent=error.message}};
$('#productForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,data={name:f.name.value,category:f.category.value,price_cents:Math.round(+f.price.value*100),inventory:+f.inventory.value,description:f.description.value,variants:f.variants.value.split(',').map(x=>x.trim()).filter(Boolean),image_url:f.image_url.value,active:f.active.checked,featured:f.featured.checked};try{const editing=!!f.id.value;await api(`/api/products${editing?`?id=${f.id.value}`:''}`,{method:editing?'PATCH':'POST',body:JSON.stringify(data)});toast('Product saved');$('#productEditor').hidden=true;await load()}catch(error){$('#productError').textContent=error.message;$('#productError').hidden=false}};
$('#deleteProduct').onclick=async()=>{const id=$('#productForm').id.value;if(!id||!confirm('Delete this product? Existing order records will remain.'))return;await api(`/api/products?id=${id}`,{method:'DELETE'});$('#productEditor').hidden=true;toast('Product deleted');await load()};
$('#categoryForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button');b.disabled=true;try{await api('/api/portal?action=categories',{method:'POST',body:JSON.stringify({name:f.name.value})});f.reset();toast('Category created');await load()}catch(error){toast(error.message)}finally{b.disabled=false}};
document.addEventListener('click',async e=>{const button=e.target.closest('[data-delete-category]');if(!button)return;if(!confirm('Delete this category?'))return;try{await api(`/api/portal?action=categories&id=${button.dataset.deleteCategory}`,{method:'DELETE'});toast('Category deleted');await load()}catch(error){toast(error.message)}});
$('#connectStripe').onclick=async()=>{const b=$('#connectStripe');b.disabled=true;b.textContent='Opening Stripe…';try{const d=await api('/api/stripe/connect',{method:'POST'});location.href=d.url}catch(error){toast(error.message);b.disabled=false;b.textContent='Connect Stripe'}};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;await api('/api/settings',{method:'PATCH',body:JSON.stringify({store_name:f.store_name.value,store_description:f.store_description.value,shipping_cents:Math.round(+f.shipping.value*100)})});toast('Settings saved');await load()};
document.addEventListener('click',e=>{const p=e.target.closest('[data-product]'),o=e.target.closest('[data-order]');if(p)editProduct(state.products.find(x=>x.id===p.dataset.product));if(o){const order=state.orders.find(x=>x.id===o.dataset.order),f=$('#orderForm');f.id.value=order.id;f.fulfillment_status.value=order.fulfillment_status;f.tracking_number.value=order.tracking_number||'';f.tracking_url.value=order.tracking_url||'';f.notes.value=order.notes||'';$('#orderEditor').hidden=false;$('#orderEditor').scrollIntoView({behavior:'smooth'})}});$('#closeOrder').onclick=()=>$('#orderEditor').hidden=true;$('#refreshOrders').onclick=load;
$('#orderForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;await api(`/api/orders?id=${f.id.value}`,{method:'PATCH',body:JSON.stringify({fulfillment_status:f.fulfillment_status.value,tracking_number:f.tracking_number.value,tracking_url:f.tracking_url.value,notes:f.notes.value})});toast('Order updated');$('#orderEditor').hidden=true;await load()};
function putToDrive(url,file,onProgress){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('PUT',url);xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');xhr.upload.onprogress=e=>{if(e.lengthComputable)onProgress(Math.round(e.loaded/e.total*100))};xhr.onload=()=>{if(xhr.status>=200&&xhr.status<300){try{resolve(JSON.parse(xhr.responseText))}catch{reject(new Error('Drive returned an invalid upload response.'))}}else reject(new Error(`Upload failed (${xhr.status}).`))};xhr.onerror=()=>reject(new Error('The upload was interrupted.'));xhr.send(file)})}
async function uploadVideo(projectId,kind,file,onProgress){const session=await api('/api/portal?action=video-upload-session',{method:'POST',body:JSON.stringify({project_id:projectId,kind,name:file.name,size:file.size,type:file.type||'application/octet-stream'})});const driveFile=await putToDrive(session.session_url,file,onProgress);await api('/api/portal?action=video-complete',{method:'POST',body:JSON.stringify({project_id:projectId,kind,file_id:driveFile.id})})}
$('#videoForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,file=f.file.files[0],button=f.querySelector('button[type=submit]');if(!file)return;button.disabled=true;try{const created=await api('/api/portal?action=videos',{method:'POST',body:JSON.stringify({title:f.title.value,notes:f.notes.value})});await uploadVideo(created.project.id,'original',file,p=>{$('#videoProgress').style.width=`${p}%`;$('#videoProgressText').textContent=`Uploading ${p}%`});toast('Video uploaded');f.reset();$('#videoProgress').style.width='0';$('#videoProgressText').textContent='';await load()}catch(error){toast(error.message)}finally{button.disabled=false}};
$('#refreshVideos').onclick=load;
$('#clearVideoHistory').onclick=async()=>{if(!state.videos.length){toast('Upload history is already empty');return}if(!confirm('Clear all upload history? This removes the project list from Runnin\' Point but keeps the video files in Google Drive.'))return;const button=$('#clearVideoHistory');button.disabled=true;try{const result=await api('/api/portal?action=videos',{method:'DELETE'});toast(`${result.deleted} project${result.deleted===1?'':'s'} cleared`);await load()}catch(error){toast(error.message)}finally{button.disabled=false}};
$('#googleForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await api('/api/portal?action=google-settings',{method:'POST',body:JSON.stringify({client_id:f.client_id.value,client_secret:f.client_secret.value})});f.client_secret.value='';toast('Google credentials saved');await loadDeveloper()}catch(error){toast(error.message)}};
$('#connectGoogle').onclick=async()=>{try{const d=await api('/api/portal?action=google-connect',{method:'POST'});location.href=d.url}catch(error){toast(error.message)}};
$('#accountForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await api('/api/portal?action=accounts',{method:'POST',body:JSON.stringify({username:f.username.value,password:f.password.value,role:f.role.value})});f.reset();toast('Account created');await loadDeveloper()}catch(error){toast(error.message)}};
$('#refreshLogs').onclick=loadDeveloper;
document.addEventListener('click',async e=>{const finalButton=e.target.closest('[data-final]'),toggle=e.target.closest('[data-toggle-account]'),del=e.target.closest('[data-delete-account]');if(finalButton){const input=$(`#final-${finalButton.dataset.final}`);input.click();input.onchange=async()=>{const file=input.files[0];if(!file)return;finalButton.disabled=true;finalButton.textContent='Uploading 0%';try{await uploadVideo(finalButton.dataset.final,'final',file,p=>finalButton.textContent=`Uploading ${p}%`);toast('Final edit uploaded');await load()}catch(error){toast(error.message)}finally{finalButton.disabled=false}}}if(toggle){try{await api(`/api/portal?action=accounts&id=${toggle.dataset.toggleAccount}`,{method:'PATCH',body:JSON.stringify({active:toggle.dataset.active!=='true'})});await loadDeveloper()}catch(error){toast(error.message)}}if(del){if(!confirm('Delete this account?'))return;try{await api(`/api/portal?action=accounts&id=${del.dataset.deleteAccount}`,{method:'DELETE'});await loadDeveloper()}catch(error){toast(error.message)}}});
document.addEventListener('change',async e=>{const select=e.target.closest('[data-video-status]');if(!select)return;try{await api(`/api/portal?action=videos&id=${select.dataset.videoStatus}`,{method:'PATCH',body:JSON.stringify({status:select.value})});toast('Video status updated');await load()}catch(error){toast(error.message)}});
(async()=>{try{const session=await api('/api/auth/session');state.currentUser={username:session.username,role:session.role};showApp();await load();const q=new URLSearchParams(location.search);if(q.has('stripe'))toast('Stripe status refreshed');if(q.get('google')==='connected'){toast('Google Drive connected');setView('developer')}if(q.get('google')==='error')toast(q.get('message')||'Google connection failed')}catch{showLogin()}})();

