const state={products:[],orders:[],settings:null,stripe:null};const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((c||0)/100);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
async function api(url,options={}){const r=await fetch(url,{...options,headers:{...(options.body instanceof Blob?{}:{'Content-Type':'application/json'}),...options.headers}});const d=await r.json().catch(()=>({}));if(r.status===401){showLogin();throw new Error('Please sign in again.')}if(!r.ok)throw new Error(d.error||'Request failed');return d}
function showLogin(){ $('#loginView').hidden=false;$('#appView').hidden=true }function showApp(){ $('#loginView').hidden=true;$('#appView').hidden=false }
function setView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#viewTitle').textContent={dashboard:'Overview',products:'Products',orders:'Orders',settings:'Settings'}[name]}
function render(){
  $('#statSales').textContent=money(state.orders.filter(o=>o.payment_status==='paid').reduce((s,o)=>s+o.amount_total,0));$('#statOrders').textContent=state.orders.filter(o=>o.payment_status==='paid').length;$('#statProducts').textContent=state.products.filter(p=>p.active).length;$('#statShipping').textContent=state.orders.filter(o=>o.payment_status==='paid'&&!['shipped','delivered','cancelled'].includes(o.fulfillment_status)).length;
  const orderRow=o=>`<tr><td><b>${new Date(o.created_at).toLocaleDateString()}</b><br><small>${o.id.slice(0,8)}</small></td><td>${esc(o.customer_name||'—')}<br><small>${esc(o.customer_email||'')}</small></td><td>${o.items.map(i=>`${i.quantity}× ${esc(i.product_name)}${i.variant?` (${esc(i.variant)})`:''}`).join('<br>')}</td><td>${money(o.amount_total)}</td><td><span class="badge ${esc(o.payment_status)}">${esc(o.payment_status)}</span></td><td><span class="badge ${esc(o.fulfillment_status)}">${esc(o.fulfillment_status)}</span></td><td><button class="mini-button" data-order="${o.id}">Manage</button></td></tr>`;
  $('#orderRows').innerHTML=state.orders.length?state.orders.map(orderRow).join(''):'<tr><td colspan="7">No orders yet.</td></tr>';$('#recentOrders').innerHTML=state.orders.length?state.orders.slice(0,5).map(o=>`<tr><td>${o.id.slice(0,8)}</td><td>${esc(o.customer_name||o.customer_email||'Pending')}</td><td>${money(o.amount_total)}</td><td><span class="badge ${esc(o.payment_status)}">${esc(o.payment_status)}</span></td><td><span class="badge ${esc(o.fulfillment_status)}">${esc(o.fulfillment_status)}</span></td></tr>`).join(''):'<tr><td colspan="5">No orders yet.</td></tr>';
  $('#productRows').innerHTML=state.products.length?state.products.map(p=>`<tr><td><div style="display:flex;gap:12px;align-items:center">${p.image_url?`<img class="thumb" src="${esc(p.image_url)}" alt="">`:'<span class="thumb"></span>'}<div><b>${esc(p.name)}</b><br><small>${esc(p.category)}</small></div></div></td><td>${money(p.price_cents)}</td><td>${p.inventory}</td><td><span class="badge">${p.active?'Live':'Hidden'}</span></td><td><button class="mini-button" data-product="${p.id}">Edit</button></td></tr>`).join(''):'<tr><td colspan="5">Add the first product to open the shop.</td></tr>';
  const s=state.stripe||{};$('#stripeStatus').textContent=s.charges_enabled?'Ready for payments':s.connected?'Finish setup':'Not connected';$('#stripeStatus').classList.toggle('good',!!s.charges_enabled);$('#connectStripe').textContent=s.connected?'Continue Stripe setup':'Connect Stripe';
}
const DEMO_PRODUCTS=[{id:'11111111-1111-4111-8111-111111111111',name:'Point Study No. 01',description:'Original mixed-media basketball study.',price_cents:18000,image_url:'',category:'Original Art',variants:['Original'],inventory:1,active:true,featured:true},{id:'22222222-2222-4222-8222-222222222222',name:'Run the Floor Print',description:'Signed archival print.',price_cents:4500,image_url:'',category:'Prints',variants:['11 × 14','18 × 24'],inventory:24,active:true,featured:false},{id:'33333333-3333-4333-8333-333333333333',name:'Runnin’ Point Tee',description:'Heavyweight cotton tee.',price_cents:3800,image_url:'',category:'Merch',variants:['S','M','L','XL','2XL'],inventory:40,active:true,featured:false}];
async function load(){try{const [p,o,s,st]=await Promise.all([api('/api/products?admin=1'),api('/api/orders'),api('/api/settings'),api('/api/stripe/status').catch(()=>({connected:false}))]);state.products=p.products;state.orders=o.orders;state.settings=s.settings;state.stripe=st}catch{state.products=DEMO_PRODUCTS;state.orders=[];state.settings={store_name:"Runnin' Point Shop",store_description:'Preview collection — connect the database to save changes.',shipping_cents:0};state.stripe={connected:false};toast('Preview mode — database setup is still required')}const f=$('#settingsForm');f.store_name.value=state.settings.store_name;f.store_description.value=state.settings.store_description;f.shipping.value=(state.settings.shipping_cents/100).toFixed(2);render()}
function editProduct(product){const f=$('#productForm');f.reset();f.id.value=product?.id||'';f.name.value=product?.name||'';f.category.value=product?.category||'Art';f.price.value=product?(product.price_cents/100).toFixed(2):'';f.inventory.value=product?.inventory??0;f.description.value=product?.description||'';f.variants.value=(product?.variants||[]).join(', ');f.image_url.value=product?.image_url||'';f.active.checked=product?.active??true;f.featured.checked=product?.featured??false;$('#editorTitle').textContent=product?'Edit product':'Add product';$('#deleteProduct').hidden=!product;$('#uploadPreview').innerHTML=product?.image_url?`<img src="${esc(product.image_url)}" alt="">`:'Choose an image below';$('#productEditor').hidden=false;$('#productEditor').scrollIntoView({behavior:'smooth'})}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;$('#loginError').hidden=true;try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:f.username.value,password:f.password.value})});showApp();await load()}catch(error){$('#loginError').textContent=error.message;$('#loginError').hidden=false}};
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$$('[data-jump]').forEach(b=>b.onclick=()=>setView(b.dataset.jump));$('#logout').onclick=async()=>{await api('/api/auth/logout',{method:'POST'});showLogin()};$('#newProduct').onclick=()=>editProduct();$('#closeEditor').onclick=()=>$('#productEditor').hidden=true;
$('#imageFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('#uploadPreview').textContent='Uploading…';try{const d=await api('/api/upload',{method:'POST',headers:{'Content-Type':file.type},body:file});$('#productForm').image_url.value=d.url;$('#uploadPreview').innerHTML=`<img src="${esc(d.url)}" alt="">`}catch(error){$('#uploadPreview').textContent=error.message}};
$('#productForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,data={name:f.name.value,category:f.category.value,price_cents:Math.round(+f.price.value*100),inventory:+f.inventory.value,description:f.description.value,variants:f.variants.value.split(',').map(x=>x.trim()).filter(Boolean),image_url:f.image_url.value,active:f.active.checked,featured:f.featured.checked};try{const editing=!!f.id.value;await api(`/api/products${editing?`?id=${f.id.value}`:''}`,{method:editing?'PATCH':'POST',body:JSON.stringify(data)});toast('Product saved');$('#productEditor').hidden=true;await load()}catch(error){$('#productError').textContent=error.message;$('#productError').hidden=false}};
$('#deleteProduct').onclick=async()=>{const id=$('#productForm').id.value;if(!id||!confirm('Delete this product? Existing order records will remain.'))return;await api(`/api/products?id=${id}`,{method:'DELETE'});$('#productEditor').hidden=true;toast('Product deleted');await load()};
$('#connectStripe').onclick=async()=>{const b=$('#connectStripe');b.disabled=true;b.textContent='Opening Stripe…';try{const d=await api('/api/stripe/connect',{method:'POST'});location.href=d.url}catch(error){toast(error.message);b.disabled=false;b.textContent='Connect Stripe'}};
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;await api('/api/settings',{method:'PATCH',body:JSON.stringify({store_name:f.store_name.value,store_description:f.store_description.value,shipping_cents:Math.round(+f.shipping.value*100)})});toast('Settings saved');await load()};
document.addEventListener('click',e=>{const p=e.target.closest('[data-product]'),o=e.target.closest('[data-order]');if(p)editProduct(state.products.find(x=>x.id===p.dataset.product));if(o){const order=state.orders.find(x=>x.id===o.dataset.order),f=$('#orderForm');f.id.value=order.id;f.fulfillment_status.value=order.fulfillment_status;f.tracking_number.value=order.tracking_number||'';f.tracking_url.value=order.tracking_url||'';f.notes.value=order.notes||'';$('#orderEditor').hidden=false;$('#orderEditor').scrollIntoView({behavior:'smooth'})}});$('#closeOrder').onclick=()=>$('#orderEditor').hidden=true;$('#refreshOrders').onclick=load;
$('#orderForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;await api(`/api/orders?id=${f.id.value}`,{method:'PATCH',body:JSON.stringify({fulfillment_status:f.fulfillment_status.value,tracking_number:f.tracking_number.value,tracking_url:f.tracking_url.value,notes:f.notes.value})});toast('Order updated');$('#orderEditor').hidden=true;await load()};
(async()=>{try{await api('/api/auth/session');showApp();await load();if(new URLSearchParams(location.search).has('stripe'))toast('Stripe status refreshed')}catch{showLogin()}})();

