import { Readable } from 'node:stream';
import bcrypt from 'bcryptjs';
import { z } from 'zod';
import { createOAuthState, requireAdmin, requireDeveloper, verifyOAuthState } from './_lib/auth.js';
import { audit } from './_lib/audit.js';
import { encrypt } from './_lib/crypto.js';
import { db, ensureSchema } from './_lib/db.js';
import { accessToken, driveFetch, googleSettings } from './_lib/google.js';
import { fail, getOrigin, json } from './_lib/response.js';
export const config={api:{responseLimit:false}};
const uuid=z.string().uuid();

async function categories(req,res,user,sql){if(req.method==='GET')return json(res,200,{categories:await sql`SELECT id,name FROM product_categories ORDER BY lower(name)`});if(req.method==='POST'){const{name}=z.object({name:z.string().trim().min(1).max(50)}).parse(req.body),existing=await sql`SELECT id FROM product_categories WHERE lower(name)=lower(${name}) LIMIT 1`;if(existing.length)return json(res,409,{error:'That category already exists.'});const[category]=await sql`INSERT INTO product_categories(name) VALUES(${name}) RETURNING id,name`;return json(res,201,{category})}const id=uuid.parse(req.query?.id),[category]=await sql`SELECT name FROM product_categories WHERE id=${id}`;if(!category)return json(res,404,{error:'Category not found.'});const[{count}]=await sql`SELECT count(*)::int count FROM products WHERE lower(category)=lower(${category.name})`;if(count)return json(res,409,{error:'Move or delete products in this category first.'});await sql`DELETE FROM product_categories WHERE id=${id}`;return json(res,200,{ok:true})}

async function videos(req,res,user,sql){if(req.method==='GET')return json(res,200,{projects:await sql`SELECT * FROM video_projects ORDER BY created_at DESC LIMIT 250`});if(req.method==='POST'){const b=z.object({title:z.string().trim().min(2).max(160),notes:z.string().trim().max(4000).default('')}).parse(req.body),[project]=await sql`INSERT INTO video_projects(title,notes,created_by) VALUES(${b.title},${b.notes},${user.username}) RETURNING *`;await audit(user.username,'video.created',{id:project.id,title:project.title});return json(res,201,{project})}if(req.method==='DELETE'){const deleted=await sql`DELETE FROM video_projects RETURNING id`;await audit(user.username,'video.history_cleared',{count:deleted.length});return json(res,200,{ok:true,deleted:deleted.length})}const id=uuid.parse(req.query?.id),{status}=z.object({status:z.enum(['waiting_for_upload','uploaded','editing','review','complete'])}).parse(req.body),[project]=await sql`UPDATE video_projects SET status=${status},updated_at=now() WHERE id=${id} RETURNING *`;await audit(user.username,'video.status_changed',{id,status});return json(res,200,{project})}

async function uploadSession(req,res,user){const b=z.object({project_id:uuid,kind:z.enum(['original','final']),name:z.string().trim().min(1).max(240),size:z.number().int().positive().max(107374182400),type:z.string().trim().max(200).default('application/octet-stream')}).parse(req.body);if(b.kind==='final'&&user.role!=='developer')return json(res,403,{error:'Only the developer can upload final edits.'});const{token,folderId}=await accessToken();if(!folderId)return json(res,503,{error:'Google Drive folder is not configured.'});const response=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable&fields=id,name,size,mimeType',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json; charset=UTF-8','X-Upload-Content-Type':b.type||'application/octet-stream','X-Upload-Content-Length':String(b.size)},body:JSON.stringify({name:b.name,parents:[folderId],appProperties:{rp_project_id:b.project_id,rp_kind:b.kind}})});if(!response.ok){const d=await response.json().catch(()=>({}));throw new Error(d.error?.message||'Could not begin the Drive upload.')}return json(res,200,{session_url:response.headers.get('location')})}

async function completeUpload(req,res,user,sql){const b=z.object({project_id:uuid,kind:z.enum(['original','final']),file_id:z.string().min(5).max(200)}).parse(req.body);if(b.kind==='final'&&user.role!=='developer')return json(res,403,{error:'Only the developer can upload final edits.'});const response=await driveFetch(`/drive/v3/files/${encodeURIComponent(b.file_id)}?fields=id,name,size,mimeType,appProperties`),file=await response.json();if(!response.ok||file.appProperties?.rp_project_id!==b.project_id||file.appProperties?.rp_kind!==b.kind)return json(res,400,{error:'Drive could not verify this project file.'});const[project]=b.kind==='original'?await sql`UPDATE video_projects SET original_file_id=${file.id},original_name=${file.name},original_size=${Number(file.size||0)},status='uploaded',updated_at=now() WHERE id=${b.project_id} RETURNING *`:await sql`UPDATE video_projects SET final_file_id=${file.id},final_name=${file.name},final_size=${Number(file.size||0)},status='review',updated_at=now() WHERE id=${b.project_id} RETURNING *`;await audit(user.username,`video.${b.kind}_uploaded`,{id:b.project_id,name:file.name,size:file.size});return json(res,200,{project})}

async function download(req,res,user,sql){const id=uuid.parse(req.query?.id),kind=z.enum(['original','final']).parse(req.query?.kind),[p]=await sql`SELECT * FROM video_projects WHERE id=${id}`,fileId=kind==='original'?p?.original_file_id:p?.final_file_id,name=kind==='original'?p?.original_name:p?.final_name;if(!fileId)return json(res,404,{error:'File not found.'});const headers={};if(req.headers.range)headers.Range=req.headers.range;const response=await driveFetch(`/drive/v3/files/${encodeURIComponent(fileId)}?alt=media`,{headers});if(!response.ok)return json(res,response.status,{error:'Drive download failed.'});res.statusCode=response.status;res.setHeader('Content-Type',response.headers.get('content-type')||'application/octet-stream');res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(name||'video')}`);for(const h of ['content-length','content-range','accept-ranges']){const v=response.headers.get(h);if(v)res.setHeader(h,v)}await audit(user.username,'video.downloaded',{id,kind,name});Readable.fromWeb(response.body).pipe(res)}

async function accounts(req,res,user,sql){if(req.method==='GET')return json(res,200,{accounts:await sql`SELECT id,username,role,active,created_at FROM admin_users ORDER BY created_at`});if(req.method==='POST'){const b=z.object({username:z.string().trim().min(2).max(80).regex(/^[a-zA-Z0-9_-]+$/),password:z.string().min(4).max(200),role:z.enum(['admin','developer']).default('admin')}).parse(req.body),hash=await bcrypt.hash(b.password,12),[account]=await sql`INSERT INTO admin_users(username,password_hash,role) VALUES(${b.username.toLowerCase()},${hash},${b.role}) RETURNING id,username,role,active,created_at`;await audit(user.username,'account.created',{username:account.username,role:account.role});return json(res,201,{account})}const id=uuid.parse(req.query?.id),[target]=await sql`SELECT username FROM admin_users WHERE id=${id}`;if(!target)return json(res,404,{error:'Account not found.'});if(target.username===user.username)return json(res,400,{error:'You cannot modify your current account.'});if(req.method==='DELETE'){await sql`DELETE FROM admin_users WHERE id=${id}`;await audit(user.username,'account.deleted',{username:target.username});return json(res,200,{ok:true})}const{active}=z.object({active:z.boolean()}).parse(req.body),[account]=await sql`UPDATE admin_users SET active=${active},updated_at=now() WHERE id=${id} RETURNING id,username,role,active,created_at`;await audit(user.username,'account.updated',{username:account.username,active});return json(res,200,{account})}

async function googleSettingsHandler(req,res,user,sql){if(req.method==='POST'){const b=z.object({client_id:z.string().trim().min(10),client_secret:z.string().trim().min(6)}).parse(req.body);await sql`UPDATE integration_settings SET google_client_id=${encrypt(b.client_id)},google_client_secret=${encrypt(b.client_secret)},google_refresh_token=NULL,google_folder_id=NULL,google_email=NULL,updated_at=now() WHERE id=1`;await audit(user.username,'google.credentials_saved');return json(res,200,{ok:true})}const s=await googleSettings();return json(res,200,{configured:!!(s.clientId&&s.clientSecret),connected:!!s.refreshToken,email:s.email,folder_id:s.folderId,callback_url:`${getOrigin(req)}/api/google-callback`})}

async function googleConnect(req,res,user){const s=await googleSettings();if(!s.clientId||!s.clientSecret)return json(res,400,{error:'Save Google OAuth credentials first.'});const state=await createOAuthState(user),params=new URLSearchParams({client_id:s.clientId,redirect_uri:`${getOrigin(req)}/api/google-callback`,response_type:'code',scope:'https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/userinfo.email',access_type:'offline',prompt:'consent',include_granted_scopes:'true',state});return json(res,200,{url:`https://accounts.google.com/o/oauth2/v2/auth?${params}`})}

async function googleCallback(req,res){try{const state=await verifyOAuthState(req.query?.state),s=await googleSettings(),redirectUri=`${getOrigin(req)}/api/google-callback`,tr=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code:req.query?.code,client_id:s.clientId,client_secret:s.clientSecret,redirect_uri:redirectUri,grant_type:'authorization_code'})}),tokens=await tr.json();if(!tr.ok||!tokens.refresh_token)throw new Error(tokens.error_description||'Google did not return offline access.');const headers={Authorization:`Bearer ${tokens.access_token}`,'Content-Type':'application/json'},fr=await fetch('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',headers,body:JSON.stringify({name:'Runnin Point Video Portal',mimeType:'application/vnd.google-apps.folder'})}),folder=await fr.json();if(!fr.ok)throw new Error(folder.error?.message||'Could not create Drive folder');const pr=await fetch('https://www.googleapis.com/oauth2/v2/userinfo',{headers:{Authorization:`Bearer ${tokens.access_token}`}}),profile=await pr.json(),sql=db();await sql`UPDATE integration_settings SET google_refresh_token=${encrypt(tokens.refresh_token)},google_folder_id=${folder.id},google_email=${profile.email||null},updated_at=now() WHERE id=1`;await audit(state.username,'google.connected',{email:profile.email});res.statusCode=302;res.setHeader('Location','/admin?google=connected');res.end()}catch(error){console.error(error);res.statusCode=302;res.setHeader('Location',`/admin?google=error&message=${encodeURIComponent(error.message)}`);res.end()}}

export default async function handler(req,res){const action=req.query?.action;try{await ensureSchema();if(action==='google-callback')return googleCallback(req,res);const user=await requireAdmin(req),sql=db();if(action==='categories')return categories(req,res,user,sql);if(action==='videos')return videos(req,res,user,sql);if(action==='video-upload-session')return uploadSession(req,res,user);if(action==='video-complete')return completeUpload(req,res,user,sql);if(action==='video-download')return download(req,res,user,sql);if(['accounts','logs','google-settings','google-connect'].includes(action))await requireDeveloper(req);if(action==='accounts')return accounts(req,res,user,sql);if(action==='logs')return json(res,200,{logs:await sql`SELECT * FROM activity_logs ORDER BY created_at DESC LIMIT 250`});if(action==='google-settings')return googleSettingsHandler(req,res,user,sql);if(action==='google-connect')return googleConnect(req,res,user);return json(res,404,{error:'Portal action not found.'})}catch(error){return fail(res,error)}}
